### ISSUE TITLE
Append changelog to build notes

### ISSUE THREAD

**Issue by inada-s** [KLab/emlauncher-jenkins-plugin#3]
Append changelog to build notesを正しく反映して欲しい

**Comment by kazuhidet** [comment]
まだpull requestはしていませんが、以下のパッチを加えればemlauncherのdescriptionにSCMのchange logを反映させる事ができます。

--- a/src/main/java/emlauncher/TestflightRecorder.java
+++ b/src/main/java/emlauncher/TestflightRecorder.java
@@ -285,7 +285,9 @@ public class TestflightRecorder extends Recorder {
         ur.apiToken = vars.expand(Secret.toString(hostTokenPair.getApiToken()));
         ur.sslEnable = hostTokenPair.getSslEnable();
         ur.title = vars.expand(title);
-        ur.description = vars.expand(description);
+	// Add SCM change log to description. (if needed)
+        //ur.description = vars.expand(description);
+	ur.description = createDescription(vars.expand(description), build.getChangeSet());
         ur.tags = vars.expand(tags);
         ur.notifyTeam = notifyTeam;
         ProxyConfiguration proxy = getProxy();
@@ -312,12 +314,12 @@ public class TestflightRecorder extends Recorder {
     }

     // Append the changelog if we should and can
-    private String createBuildNotes(String buildNotes, final ChangeLogSet<?> changeSet) {
+    private String createDescription(String description, final ChangeLogSet<?> changeSet) {
         if (appendChangelog) {
             StringBuilder stringBuilder = new StringBuilder();

             // Show the build notes first
-            stringBuilder.append(buildNotes);
+            stringBuilder.append(description);

             // Then append the changelog
             stringBuilder.append("\n\n")
@@ -332,9 +334,9 @@ public class TestflightRecorder extends Recorder {

                 entryNumber++;
             }
-            buildNotes = stringBuilder.toString();
+            description = stringBuilder.toString();
         }
-        return buildNotes;
+        return description;
     }

     @Override

**Comment by kazuhidet** [comment]
この変更は PR#6 に含まれているのでクローズでいいと思います。

**Comment by gutio** [comment]
ありがとうございます。
Closeします。
